# Generated by Django 4.0.10 on 2025-01-12 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expense_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_tracker', '0002_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin User', 'Admin User'), ('Standard User', 'Standard User')], default='Standard User', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_user',
            field=models.ForeignKey(default=expense_tracker.models.getSystemUser, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.systemuser'),
        ),
    ]
