# Generated by Django 4.0.10 on 2025-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0005_alter_systemuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
