# Generated by Django 4.0.10 on 2025-01-14 14:52

from django.db import migrations, models
import django.db.models.deletion
import expense_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0006_systemuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.category')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(default=expense_tracker.models.getSubCategory, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.subcategory'),
        ),
    ]
