# Generated by Django 4.0.10 on 2025-01-16 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_subcategory_transaction_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='createOn',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
