# Generated by Django 4.0.10 on 2025-01-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0008_systemuser_createon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='createOn',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='status',
        ),
    ]
